.TH LDAP_PASSWD 1 "29 Apr 2016"
.
.SH NAME
.hy 0
.
.BI ldap_passwd
\- change account password.
.
.SH SYNOPSIS
.B ldap_passwd
[OPTION] {ACCOUNT FORMAT}

.B {ACCOUNT FROMAT}
.IP
# uid=user,ou=People,dc=domain,dc=com
.br
.BI user@domian.com
.sp
.
.SH DESCRIPTION
ldap_passwd changes password of user account

.TP
change password of current login user:
.B ldap_passwd
.TP
change password of current login user with md5 hash algorithm:
.B ldap_passwd
-m md5
.TP
change password of LDAP_USER with BASE DN 'dc=DOMAIN,dc=COM'. Only root can change other account:
.B ldap_passwd
LADP_USER@DOMAIN.COM
.
.SH OPTIONS
.IP -g
assigned group ou. The default value is set 'Group' in ldap-auth-utils.conf(5).
.IP -h
display help message and exit
.IP -m
hash algorithm. md5 or sha512. Teh default is sha512.
.IP -u
assigned group ou. The default value is set 'People' in ldap-auth-utils.conf(5).
.
.SH "EXIT STATUS"
Normally, the exit status is 0 if no errors, and 1 otherwise.
.
.SH COPYRIGHT
Copyright 2016 JoungKyun.Kim
.PP
This is free software;
see the source for copying conditions.
There is NO warranty;
not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.
.SH BUGS
bug tracker is located at <https://github.com/Joungkyun/ldap-auth-utils/issues>.
.
.SH "SEE ALSO"
.BR ldap-auth-utils.conf(5),
.BR ldap_auth_init(1),
.BR ldap_auth(1),
.BR ldap_ssl(1),
.BR ldap_grpadd(1),
.BR ldap_grpdel(1),
.BR ldap_host_manage(1),
.BR ldap_replica(1),
.BR ldap_useradd(1),
.BR ldap_userdel(1)
