.TH LDAP_REPLICA 1 "29 Apr 2016"
.
.SH NAME
.hy 0
.
.BI ldap_replica
\- manages ldap replication
.
.SH SYNOPSIS
.B ldap_replica
[OPTION] REPLICA_SERVER
.
.SH DESCRIPTION
ldap_replica is manages 2way multi master replication.

.TP
sync changes on ldap.target.com:
.B ldap_replica
-a -u uid=replica,ou=admin,dc=host,dc=com ldap.target.com
.TP
stop sync:
.B ldap_replica
-r
.PP
This is used many environment variables in ldap-auth-utils.conf(5). See also
.B 'man 5 ldap-auth-utils.conf'
.
.SH OPTIONS
.IP -a
add replcation configuration on this server
.IP -i
Server ID on this server. The default value is random number between 1 and 99.
.IP -h
display help message and exit
.IP -r
remove replication configuration about target server
.IP -u
replication user dn. This user has read privileges on whole database.
.
.SH "EXIT STATUS"
Normally, the exit status is 0 if no errors, and 1 otherwise.
.
.SH COPYRIGHT
Copyright 2016 JoungKyun.Kim
.PP
This is free software;
see the source for copying conditions.
There is NO warranty;
not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.
.SH BUGS
bug tracker is located at <https://github.com/Joungkyun/ldap-auth-utils/issues>.
.
.SH "SEE ALSO"
.BR ldap-auth-utils.conf(5),
.BR ldap_auth_init(1),
.BR ldap_auth(1),
.BR ldap_ssl(1),
.BR ldap_grpadd(1),
.BR ldap_grpdel(1),
.BR ldap_host_manage(1),
.BR ldap_passwd(1),
.BR ldap_useradd(1),
.BR ldap_userdel(1)
